import { AuthProvider } from "./context/AuthContext";
import "./globals.css";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <AuthProvider>
    <html lang="en">
      <body className={`${inter.className} flex min-h-screen`}>
        <main className="flex-1">
          {children}
        </main>
      </body>
    </html>
    </AuthProvider>
  );
}
