import Navbar from "./components/navbar/navbar";
import "./globals.css";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${inter.className} flex min-h-screen`}>

        <Navbar />

        {/* Main Content Area */}
        <main className="flex-1 p-6 bg-gray-50 lg:ml-64 overflow-y-autoauto">
          {children}
        </main>
      </body>
    </html>
  );
}
